app:
    resource: '@AppBundle/Controller/'
    type: annotation
login_check:
    path:   /login_check
    defaults: { _controller: AppBundle:Default:loginCheck }
navigate:
    path:   /navigate
    defaults: { _controller: AppBundle:Default:navigate }
app:
    resource: '@AppBundle/Controller/Frontend/'
    type: annotation
backend:
    resource: '@AppBundle/Controller/Backend/'
    type: annotation
    prefix: /redakce
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /redakce/profile
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /redakce/resetting
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /redakce/profile
