app:
    resource: '@AppBundle/Controller/'
    type: annotation
login_check:
    path:   /login_check
    defaults: { _controller: AppBundle:Default:loginCheck }
navigate:
    path:   /navigate
    defaults: { _controller: AppBundle:Default:navigate }
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
app:
    resource: '@AppBundle/Controller/Frontend/'
    type: annotation
backend:
    resource: '@AppBundle/Controller/Backend/'
    type: annotation
    prefix: /redakce
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
