# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_REDAKTOR:      [ROLE_REDAKTOR]
        ROLE_RECENZENT:     [ROLE_RECENZENT]
        ROLE_EDITOR:        [ROLE_EDITOR]
        ROLE_ADMIN:         [ROLE_ADMIN]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
            pattern: ^/
            form_login:
                login_path: fos_user_security_login
                check_path: /login_check
                failure_path: fos_user_security_login
                default_target_path: /redakce
                provider: fos_userbundle
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider
            logout:
                path: /logout
                target: fos_user_security_login
                invalidate_session:   true
            anonymous:    true


    access_control:
        - { path: ^/redakce, role: IS_AUTHENTICATED_FULLY }
