<?php

namespace AppBundle\Entity;

use Lexik\Bundle\FormFilterBundle\Filter\FilterBuilderUpdater;
use Lexik\Bundle\FormFilterBundle\Filter\Query\QueryInterface;
use Symfony\Component\Form\FormInterface;

/**
 * RecenzeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecenzeRepository extends \Doctrine\ORM\EntityRepository
{

  public function getRecenzeCount($prispevek)
  {
      $queryBuilder = $this->createQueryBuilder('r')
          ->select('COUNT(r.id)')
          ->where('r.prispevek = :prispevek AND (r.odbornost + r.zajimavost + r.aktualnost) > 7')
          ->setParameter('prispevek', $prispevek->getId());

      return $queryBuilder->getQuery()->getSingleScalarResult();
  }
}
