<?php

namespace AppBundle\Entity;

use Knp\Component\Pager\Paginator;
use Lexik\Bundle\FormFilterBundle\Filter\FilterBuilderUpdater;
use Lexik\Bundle\FormFilterBundle\Filter\Query\QueryInterface;
use Symfony\Component\Form\FormInterface;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

  private $paginator;
  private $filterBuilderUpdater;

  public function setPaginatorAndQueryUpdater(Paginator $paginator, FilterBuilderUpdater $filterBuilderUpdater)
  {
      $this->paginator = $paginator;
      $this->filterBuilderUpdater = $filterBuilderUpdater;
      return $this;
  }

  /**
   * @param $items_per_page
   * @param int $page
   * @return \Knp\Component\Pager\Pagination\PaginationInterface
   */
  public function findAllWithPaginator($items_per_page, $page = 1, FormInterface $filterForm)
  {
      $queryBuilder = $this->createQueryBuilder('u')
          ->select(['u']);

      $this->filterBuilderUpdater->addFilterConditions($filterForm, $queryBuilder);

      return $this->paginator->paginate(
          $queryBuilder->getQuery(),
          $page,
          $items_per_page,
          [
              'defaultSortFieldName' => 'u.id',
              'defaultSortDirection' => 'DESC',
              'wrap-queries' => true
          ]
      );
  }
}
